source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra', require: 'sinatra/base'
gem 'unicorn'
gem 'erubis'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'rack-ssl'
gem 'redcarpet'
gem 'dalli'
gem 'memcachier'
gem 'builder'
gem 'sprockets'
gem 'uglifier'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'coffee-script'
gem 'stylus'
gem 'stylus-source', '0.31.0'
gem 'eco'
gem 'json', '~> 1.7.7'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'

group :development do
  gem 'thin'
  gem 'debugger', require: 'ruby-debug'
end