source 'https://rubygems.org'
ruby '2.1.1'

gem 'sinatra', require: 'sinatra/base'
gem 'unicorn'
gem 'erubis'
gem 'i18n'
gem 'activesupport'
gem 'rake'
gem 'rack-ssl'
gem 'rack-standards'
gem 'redcarpet'
gem 'dalli'
gem 'memcachier'
gem 'builder'
gem 'sprockets'
gem 'uglifier'
gem 'closure-compiler'
gem 'yui-compressor'
gem 'coffee-script'
gem 'stylus'
gem 'stylus-source'
gem 'eco'
gem 'json'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'

group :development do
  gem 'thin'
end
